---
title: "Verkefni3"
author: "Flóki og Birnir"
date: "April 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Dæmi 1

##a)
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(kableExtra)
library(knitr)
```


```{r}
r2d <-function(r)
{
    lat <- floor(r/100)
    lon <- (r - lat * 100) %% 50
    halfb <- (r - 100 * lat - lon)/100
    lon <-  - (lon + 0.5)
    lat <- lat + 60 + halfb + 0.25
    data.frame(lat = lat, lon = lon)
}
BF<-read.csv("data98.csv", fill=TRUE)
BF<-na.omit(BF)
reitir<-unique(BF$reit)
x<-r2d(reitir)$lon
y<-r2d(reitir)$lat
plot(x,y,type='n')
text(x,y,as.character(reitir))
BF$aldur<-factor(BF$aldur)

```

```{r, eval = T}
BF$lon <- r2d(BF$reit)$lon
BF$lat <- r2d(BF$reit)$lat

skipting_lat = 65
skipting_lon = -19

BF$hafsvaedi <- with(BF, ifelse(lat >= skipting_lat & lon >= skipting_lon, "NA",

ifelse(lat <= skipting_lat & lon >= skipting_lon, "SA",

ifelse(lat <= skipting_lat & lon <= skipting_lon, "SV","NV"))))

BF$kt2 <- factor(BF$kt)
levels(BF$kt2) <- c('Ókynþroska','kynþroska','kynþroska','kynþroska','kynþroska','kynþroska')
```

##b)

```{r}
tafla<-table(BF$hafsvaedi, BF$kt2)
kable(tafla) %>%
  kable_styling(bootstrap_options = "striped", full_width = TRUE, position = "left", font_size = 16)
```
```{r}
tafla_2<-round(prop.table(table(BF$hafsvaedi, BF$kt2), 1),3)
kable(tafla_2) %>%
  kable_styling(bootstrap_options = "striped", full_width = TRUE, position = "left", font_size = 16)
```

```{r}
ggplot(BF, aes(x=BF$hafsvaedi, fill=kt2)) + geom_bar(position = "dodge") + xlab("Hafsvæði")
```


##c)
```{r}
tafla_c<-group_by(BF, aldur)%>%
  summarise("Fjöldi"= length(aldur), "Meðallengd"=mean(le, na.rm=TRUE),"Meðalþyngd"=mean(osl, na.rm=TRUE), "Staðalfrávik lengdar"=sd(le, na.rm=TRUE))
kable(tafla_c) %>%
  kable_styling(bootstrap_options = "striped", full_width = TRUE, position = "left", font_size = 16)
```


```{r}
medal <- group_by(BF, aldur) %>% 
  summarise(le = mean(le, na.rm = TRUE))

ggplot(BF, aes(x=aldur, y=le)) +
  geom_point(colour = "green") + xlab("Aldur sem samfelld breyta") + ylab("Lengd") +
  geom_point(data = medal, size = 3.5, colour = "red")
```

ggplot(BF, aes(a))